import { mkdir, rm } from 'node:fs/promises';
import { defaultRuntimeConfig, type RuntimeConfigStore } from '../config/runtimeConfig';
import type { AppPaths } from '../paths/appPaths';

type ResetDependencies = {
  paths: AppPaths;
  configStore: Pick<RuntimeConfigStore, 'save'>;
  clearBusinessData(): Promise<void>;
  stopBackend(): Promise<void>;
  clearBrowserStorage(): Promise<void>;
  startBackend(): Promise<void>;
};

export async function resetDesktopData(dependencies: ResetDependencies) {
  // Complete the backend's transactional reset before clearing shell preferences.
  await dependencies.clearBusinessData();
  await dependencies.stopBackend();
  try {
    await dependencies.configStore.save(defaultRuntimeConfig());
    await dependencies.clearBrowserStorage();
    // These paths are generated by AppPaths; dataset and backup paths never enter this list.
    for (const directory of [dependencies.paths.cacheDir, dependencies.paths.tempDir]) {
      await rm(directory, { recursive: true, force: true });
      await mkdir(directory, { recursive: true });
    }
  } finally {
    // A storage cleanup failure must still leave the application able to serve its error UI.
    await dependencies.startBackend();
  }
}
