app:
  dictionary:
    enabled: ${APP_DICTIONARY_ENABLED:false}
    datasource:
      url: "${APP_DICTIONARY_DB_URL:jdbc:sqlite:data/dictionary.sqlite}"
      driver-class-name: org.sqlite.JDBC

logging:
  level:
    org.springframework.jdbc.datasource.init: INFO
    org.hibernate.SQL: INFO
